// generated by script/route.js
/* eslint-disable */
export default [
    {
        dir: 'CSS',
        name: 'CSSBackground',
        path: 'CSS-Background',
        file: 'Background',
        label: 'background',
        component: () => import('@/views/CSS/Background.vue'),
    },
    {
        dir: 'CSS',
        name: 'CSSMarqueeTag',
        path: 'CSS-MarqueeTag',
        file: 'MarqueeTag',
        label: 'marqueetag',
        component: () => import('@/views/CSS/MarqueeTag.vue'),
    },
    {
        dir: 'CSS',
        name: 'CSSMask',
        path: 'CSS-Mask',
        file: 'Mask',
        label: 'mask',
        component: () => import('@/views/CSS/Mask.vue'),
    },
    {
        dir: 'JavaScript',
        name: 'JavaScriptInputIME',
        path: 'JavaScript-InputIME',
        file: 'InputIME',
        label: 'inputime',
        component: () => import('@/views/JavaScript/InputIME.vue'),
    },
    {
        dir: 'JavaScript',
        name: 'JavaScriptTask',
        path: 'JavaScript-Task',
        file: 'Task',
        label: 'task',
        component: () => import('@/views/JavaScript/Task.vue'),
    },
    {
        dir: 'Vue',
        name: 'VueSuspense',
        path: 'Vue-Suspense',
        file: 'Suspense',
        label: 'suspense',
        component: () => import('@/views/Vue/Suspense.vue'),
    },
    {
        dir: 'Vue',
        name: 'VueTeleport',
        path: 'Vue-Teleport',
        file: 'Teleport',
        label: 'teleport',
        component: () => import('@/views/Vue/Teleport.vue'),
    }
]