// generated by script/route.js
/* eslint-disable */
export default [
    {
        dir: 'CSS',
        name: 'CSSBackground.vue',
        path: 'CSS-Background.vue',
        file: 'Background.vue',
        label: 'background',
        component: () => import('@/views/CSS/Background.vue'),
    },
    {
        dir: 'CSS',
        name: 'CSSMask.vue',
        path: 'CSS-Mask.vue',
        file: 'Mask.vue',
        label: 'mask',
        component: () => import('@/views/CSS/Mask.vue'),
    },
    {
        dir: 'JavaScript',
        name: 'JavaScriptTask.vue',
        path: 'JavaScript-Task.vue',
        file: 'Task.vue',
        label: 'task',
        component: () => import('@/views/JavaScript/Task.vue'),
    }
]