const fs = require('fs');
const path = require('path');

function readDir(dir, relativePath = '@/views/') {
    const result = { name: path.basename(dir), relativePath };

    const children = fs.readdirSync(dir).map(file => {
        const fullPath = path.join(dir, file);
        const newRelativePath = path.join(relativePath, file);
        const stat = fs.statSync(fullPath);

        if (stat.isDirectory()) {
            return readDir(fullPath, newRelativePath);
        } else if (stat.isFile() && path.extname(file) === '.vue') {
            return { name: file, relativePath: newRelativePath };
        } else {
            return null;
        }
    }).filter(child => { return child !== null; });

    if (children.length > 0) {
        result.children = children;
    }

    return result;
}

const vueFilesTree = readDir(path.resolve('./src/views'));
const result = vueFilesTree.children.filter(child => {
    return !['layout'].includes(child.name) && child.children?.length;
});
console.log(JSON.stringify(result, null, 4));

// gen vue routes
const vueRoutes = [];
result.forEach(item => {
    const { name } = item;
    item.children.forEach(child => {
        const { name: childName, relativePath: childRelativePath } = child;
        vueRoutes.push(`{
        dir: '${name}',
        name: '${name}${childName}',
        path: '${name}-${childName}',
        file: '${childName}',
        label: '${childName.replace('.vue', '').toLowerCase()}',
        component: () => import('${childRelativePath}'),
    }`);
    });
});
fs.writeFileSync(
    path.resolve('src/router/menuRoutes.ts'),
    `// generated by script/route.js
/* eslint-disable */
export default [
    ${vueRoutes.join(',\n    ')}
]`,
);
